In [ ]:
import tensorflow as tf

#Create a 1D tensor with entries from 0 to 100 in steps of 2
x = tf.range(0, 100, 2)
print(x)

In [13]:
# Create a 2D tensor with 3 rows and 3 columns, with row entries 1,1,1..., 2,2,2,..., 3,3,3,...
# y = tf.constant([1,1,1,2,2,2,3,3,3], shape=[3,3])
# variant 2
a = tf.reshape(tf.range(1,4, dtype=tf.float64), [3,1])
b = tf.ones([3,3], dtype=tf.float64)
print(a)
print(b)
y = a * b
print(y)


tf.Tensor(
[[1.]
 [2.]
 [3.]], shape=(3, 1), dtype=float64)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]], shape=(3, 3), dtype=float64)


In [17]:
#Create a 2D tensor with 3 rows and 5 columns that has the value 55 everywhere
c = tf.ones([3,5], dtype=tf.int32) * 55
print(c)

tf.Tensor(
[[55 55 55 55 55]
 [55 55 55 55 55]
 [55 55 55 55 55]], shape=(3, 5), dtype=int32)


In [31]:
#Create a 3D tensor with shape (5,4,3) with uniform random entries between 0 and 1.
d = tf.random.uniform((5,4,3),0,1) #fist shape and min and max compared to np
print(d)

tf.Tensor(
[[[0.31179297 0.8263413  0.6849456 ]
  [0.0067091  0.78749514 0.3906511 ]
  [0.29263055 0.99216926 0.95810425]
  [0.55623317 0.16466296 0.13445711]]

 [[0.13229859 0.5348098  0.57090175]
  [0.50970507 0.48252344 0.15580535]
  [0.3703227  0.49210668 0.567016  ]
  [0.2077086  0.18223882 0.99883735]]

 [[0.36950588 0.37927854 0.7723117 ]
  [0.68211746 0.39932835 0.7840713 ]
  [0.67880154 0.73395896 0.5520444 ]
  [0.10948515 0.6487982  0.9890779 ]]

 [[0.8203654  0.70470357 0.9578625 ]
  [0.02297425 0.93598676 0.6513264 ]
  [0.31663585 0.00111556 0.9212191 ]
  [0.3822806  0.77246034 0.91514194]]

 [[0.5751133  0.793342   0.4289763 ]
  [0.19118965 0.7452506  0.41762006]
  [0.8173511  0.20117116 0.6457157 ]
  [0.16484237 0.4484123  0.6057888 ]]], shape=(5, 4, 3), dtype=float32)
