In [1]:
import tensorflow as tf

#Create a 1D tensor with entries from 0 to 100 in steps of 2
x = tf.range(0, 100, 2)
print(x)

Metal device set to: Apple M1 Pro
tf.Tensor(
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98], shape=(50,), dtype=int32)


2023-02-19 14:46:16.061071: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-02-19 14:46:16.061205: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [2]:
# Create a 2D tensor with 3 rows and 3 columns, with row entries 1,1,1..., 2,2,2,..., 3,3,3,...
# y = tf.constant([1,1,1,2,2,2,3,3,3], shape=[3,3])
# variant 2
a = tf.reshape(tf.range(1,4, dtype=tf.float64), [3,1])
b = tf.ones([3,3], dtype=tf.float64)
print(a)
print(b)
y = a * b
print(y)


tf.Tensor(
[[1.]
 [2.]
 [3.]], shape=(3, 1), dtype=float64)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float64)
tf.Tensor(
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]], shape=(3, 3), dtype=float64)


In [3]:
#Create a 2D tensor with 3 rows and 5 columns that has the value 55 everywhere
c = tf.ones([3,5], dtype=tf.int32) * 55
print(c)

tf.Tensor(
[[55 55 55 55 55]
 [55 55 55 55 55]
 [55 55 55 55 55]], shape=(3, 5), dtype=int32)


In [4]:
#Create a 3D tensor with shape (5,4,3) with uniform random entries between 0 and 1.
d = tf.random.uniform((5,4,3),0,1) #fist shape and min and max compared to np
print(d)

tf.Tensor(
[[[0.45318544 0.87100565 0.4060533 ]
  [0.93715155 0.5758554  0.04351306]
  [0.11452162 0.01556396 0.01377392]
  [0.6468859  0.3669753  0.37134123]]

 [[0.70536375 0.37039876 0.26180267]
  [0.46365654 0.6424414  0.40326774]
  [0.26744008 0.11199903 0.24345219]
  [0.4638555  0.47405207 0.02891743]]

 [[0.31579232 0.63346326 0.9441289 ]
  [0.30093074 0.04362357 0.21249545]
  [0.5402416  0.45216095 0.289181  ]
  [0.41256142 0.31057942 0.35716546]]

 [[0.91609883 0.8995817  0.99516714]
  [0.3628229  0.8337654  0.89414454]
  [0.5733926  0.06359768 0.6173661 ]
  [0.2157731  0.00672996 0.56959975]]

 [[0.12389135 0.52485347 0.20850277]
  [0.34877944 0.29662895 0.5478809 ]
  [0.9876311  0.6564064  0.01008403]
  [0.1779095  0.36362898 0.6592181 ]]], shape=(5, 4, 3), dtype=float32)
