In [1]:
import numpy as np

In [2]:
# a) Give a code snippet that create two random 1D arrays of length 20, with integer entries between 0 and 3 (included). Then, the code should compute the confusion matrix from these two vectors. For-loops are forbidden here!!
t = np.random.randint(0, 4, 20)
print(t)
y = np.random.randint(0, 4, 20)
print(y)
mat = np.zeros((4,4))
np.add.at(mat, (t, y),1)
print(mat)

[0 1 1 0 1 0 0 1 3 0 3 0 2 1 0 0 2 0 2 2]
[3 3 2 0 3 0 0 0 1 0 2 0 1 3 0 0 3 0 1 0]
[[8. 0. 0. 1.]
 [1. 0. 1. 3.]
 [1. 2. 0. 1.]
 [0. 1. 1. 0.]]


In [3]:
# b) Give a code snippet that generates two 1D arrays with values from 0 to 19 (included) in ascending order. Then, the code should shuffle both arrays such that same positions contain same values after shuffling (like you would shuffle train data and labels). For-loops are forbidden here!!
x = np.arange(20)
print(x)
l = np.arange(20)
print(l)

# create a random permutation of indices
perm = np.random.permutation(len(x))


x = x[perm]
l = l[perm]
print(x)
print(l)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 7  5  1 16 12 13 10  9 14 17  3  8 19 15  4 11 18  2  6  0]
[ 7  5  1 16 12 13 10  9 14 17  3  8 19 15  4 11 18  2  6  0]


In [4]:
# c) Give a code snippet that creates a 1D array with random values from 0 to 9 (included). Then, interpret this array as scalar targets and create a one-hot representation for them, assuming 10 classes.
targets = np.random.permutation(10)
print(targets)
one_hot = np.eye(10)[targets]
print(one_hot)

[3 1 5 4 7 8 2 9 6 0]
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
#For-loops are forbidden here! Create a one-dimensional array X (with 20 elements) of random integers between 0 and 3. Create an array that contains the indices of all elements of X that are equal to 2, and print the result!
X = np.random.randint(0, 4, 20)
print(X)
print(np.where(X == 2))



[2 0 3 3 3 3 3 0 0 3 3 0 3 0 2 0 0 2 2 0]
(array([ 0, 14, 17, 18]),)
