In [1]:
#2.1 basics and slicing
import numpy as np
#Create an array X with random entries between 0 and 1, of shape (10,5,5,3). We will assume that this represents a stack of RGB image samples.
x = np.random.random((10,5,5,3))
print(x)

# Set the 3 lowermost rows of the first sample to -1
x[0, -3:] = -1
print(x)

#Slice out the 4th sample to a new array W, but keeping only every 2nd row!
w = x[3, ::2]

#copy out samples with indices 0,1,3 to a new array Z using a single assignment operation!
z = x[[0,1,3]]

#copy out all samples whose sum is smaller than 5 into a new arrav M
m = x[x.sum(axis=(1,2,3)) < 5]

[[[[0.01105872 0.93414808 0.3504687 ]
   [0.67481418 0.79212726 0.94839627]
   [0.66671329 0.9663977  0.33031755]
   [0.05636197 0.89868891 0.98257011]
   [0.15245102 0.49917856 0.52987171]]

  [[0.29497849 0.00228387 0.9661097 ]
   [0.33066403 0.76745587 0.00428416]
   [0.37954796 0.85920322 0.21586033]
   [0.0028361  0.64661601 0.2510219 ]
   [0.64695631 0.13289932 0.56613095]]

  [[0.58618162 0.15188098 0.63101773]
   [0.11001766 0.65945541 0.32252218]
   [0.37927869 0.61569401 0.45020679]
   [0.96057101 0.27911825 0.11511545]
   [0.30792508 0.06257464 0.32460608]]

  [[0.49095469 0.7378476  0.10688559]
   [0.83353178 0.85086147 0.06945078]
   [0.10136082 0.59410689 0.06852242]
   [0.14114166 0.09473942 0.7199967 ]
   [0.06024486 0.84177571 0.8768306 ]]

  [[0.40359892 0.93812357 0.47264597]
   [0.20558384 0.83073989 0.525603  ]
   [0.89911078 0.27006971 0.70039784]
   [0.5297112  0.8070808  0.68971296]
   [0.76008477 0.77693303 0.3109738 ]]]


 [[[0.5718164  0.68793559 0.66739361]


In [ ]:
#2.2
#a shuffle
X = np.arange(20)
print(X)
T = np.arange(20)
print(T)

# create a random permutation of indices
perm = np.random.permutation(len(X))

X = X[perm]
T = T[perm]
print(X)
print(T)

#b
X = np.random.randint(0, 4, 20)
print(X)
print(np.where(X == 2))

In [ ]:
#2.3
import matplotlib.pyplot as plt
import numpy as np
#a) plot the function x3 between 0 and 2 using precisely 100 support points!
x = np.linspace(0,2,100)
y = x**3
plt.plot(x,y)
plt.show()

#b) generate 9 random "images" of shape (20,20) with values between 0 and 1, and display them together in a single window!
images = np.random.rand(9,20,20)
for i in range(9):
    plt.subplot(3,3,i+1)
    plt.imshow(images[i])
plt.show()



In [ ]:
#3.1
import tensorflow as tf
def S(X):
    return tf.reduce_sum(tf.square(X), axis=1)


X = tf.constant(np.array([[-1, -1, 5], [1, 1, 3], [0, 0, 1]]), dtype=tf.float32)
print(S(X))

In [ ]:
#3.2 a
# Implement f(x) = sumi(xi) as a Python function expecting a tensor of type tf. Variable as its only parameter and compute its output for the inputs at = (1, 2, 3) and a2 = (2, 0, 2).
def f(x):
    return tf.reduce_sum(x)

a1 = tf.Variable([1, 2, 3], dtype=tf.float32)
a2 = tf.Variable([2, 0, 2], dtype=tf.float32)
print(f(a1))
print(f(a2))

#3.2 b
# Use TF to compute iand display the value of Vf, evaluated for ~ = &, and for I = dr
with tf.GradientTape() as tape:
    x = tf.Variable(a1)
    y = f(x)
print(tape.gradient(y, x))

with tf.GradientTape() as tape:
    x1 = tf.Variable(a2)
    y1 = f(x1)
print(tape.gradient(y1, x1))
