In [1]:
import numpy as np

# q: give me example of np.arrange
# a: np.arange(10) gives [0,1,2,3,4,5,6,7,8,9]
# np.arange(1,9,2) gives [1,3,5,7]
# np.arange(0,1,0.1) gives [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]

# q: give me example of np.linspace
# a: np.linspace(0,1,6) gives [0,0.2,0.4,0.6,0.8,1]
# np.linspace(0,1,5,endpoint=False) gives [0,0.25,0.5,0.75]

# q: give me example of np.random.uniform
# a: np.random.uniform(0,1,10) gives [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]
# np.random.uniform(0,1,(3,3)) gives [[0.1,0.2,0.3],[0.4,0.5,0.6],[0.7,0.8,0.9]]

# q: give me example of np.ones
# a: np.ones(3) gives [1,1,1]
# np.ones((3,3)) gives [[1,1,1],[1,1,1],[1,1,1]]

# q: give me example of np.zeros
# a: np.zeros(3) gives [0,0,0]
# np.zeros((3,3)) gives [[0,0,0],[0,0,0],[0,0,0]]

# q: give me example of np.reshape
# a: np.arange(9).reshape(3,3) gives [[0,1,2],[3,4,5],[6,7,8]]

# q: give me example of list comprehension
# a: [i for i in range(10)] gives [0,1,2,3,4,5,6,7,8,9]
# [i for i in range(10) if i%2==0] gives [0,2,4,6,8]


In [2]:
# a Create a 1D array with entries from 0 to 100 in steps of 2
a = np.arange(0, 101, 2)
print(a)


[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [3]:
# b Create a 2D array with 3 rows and 3 columns, with row entries 1,1,1..., 2,2,2,..., 3,3,3,...
b = np.ones([3, 3]) * np.arange(1, 4, 1).reshape(3, 1)
print(b)
b = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3]).reshape(3, 3)
print(b)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [4]:
# c Create a 2D array with 3 rows and 5 columns that has the value 55 every- where
c = np.ones([3, 5]) * 55
print(c)

[[55. 55. 55. 55. 55.]
 [55. 55. 55. 55. 55.]
 [55. 55. 55. 55. 55.]]


In [5]:
# d Create a 3D tensor with shape (5,4,3) with uniform random entries between 0 and 1.
d = np.random.uniform(0, 1, (5, 4, 3))
d = np.random.uniform(0, 1, 60).reshape(5, 4, 3)
print(d)

[[[0.41628085 0.80708576 0.85179655]
  [0.22955439 0.34208342 0.86410503]
  [0.51286989 0.04213571 0.0367004 ]
  [0.33773488 0.54811461 0.85400466]]

 [[0.59763534 0.10872504 0.17930632]
  [0.96179029 0.02896934 0.77422668]
  [0.74885032 0.08527381 0.28635227]
  [0.25137874 0.04222422 0.72773674]]

 [[0.41255958 0.38426028 0.41546869]
  [0.05272384 0.1273065  0.69831445]
  [0.73393888 0.66989777 0.48578334]
  [0.30105849 0.53107108 0.78188869]]

 [[0.19821024 0.21862056 0.57972313]
  [0.1123286  0.46438384 0.05352624]
  [0.05311095 0.53699592 0.28256653]
  [0.29999396 0.13715697 0.32582194]]

 [[0.48111866 0.90659643 0.63403234]
  [0.64923842 0.34411846 0.60107533]
  [0.07343478 0.12227601 0.74808688]
  [0.73355194 0.50722621 0.57597553]]]
