In [2]:
import numpy as np

vec = np.arange(1, 21, 1)
print(vec)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [4]:
# a) create a 20-element vector with entries from 1 to 20, and copy out all elements that are smaller than 10 using mask indexing!

mask = (vec < 10)
a = vec[mask]
print(a)

[1 2 3 4 5 6 7 8 9]


In [5]:
# b) create a 20-element vector with entries from 1 to 20, and set elements 1,5 and 19 to 0 using fancy indexing!
fancy = [1,5,19]
vec[fancy] = 0
print(vec)

[ 1  0  3  4  5  0  7  8  9 10 11 12 13 14 15 16 17 18 19  0]
