In [1]:

import sys

import numpy as np
import requests
import os

## download MNIST if not present in current dir!
if os.path.exists("./mnist.npz") == False:
    print("Downloading MNIST...");
    fname = 'mnist.npz'
    url = 'http://www.gepperth.net/alexander/downloads/'
    r = requests.get(url + fname)
    open(fname, 'wb').write(r.content)

## read it into 'traind' and 'trainl'
data = np.load("mnist.npz")
traind = data["arr_0"];
trainl = data["arr_2"];

In [10]:
# Examples argmax
# --------
# >>> a = np.arange(6).reshape(2,3) + 10
# >>> a
# array([[10, 11, 12],
#        [13, 14, 15]])
# >>> np.argmax(a)
# 5
# >>> np.argmax(a, axis=0)  row-wise
# array([1, 1, 1]) meaning the maximum values in each column are in the second row.
# >>> np.argmax(a, axis=1) column-wise
# array([2, 2]) maximum values in each row are in the 2 row

# a) Compute the pixel argmax for pixel 0,0 over all samples
a = np.argmax(traind[:, 0, 0])
print(a)

0


In [37]:
# b) Compute the row-wise mean over all samples
b = np.mean(traind, axis=2)
print(b)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.07058498 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [36]:
# c) Compute the column-wise sum over all samples
c = np.sum(traind, axis=1)
print(c)

[[0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]
 ...
 [0.        0.        0.        ... 0.7451172 0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 1.9291992 0.9647217 0.       ]]
