In [1]:
import numpy as np

a = np.ones([3,2,4])
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [6]:
# contractions
a1 = a.sum(axis=0)
print(a1.shape)
a2 = a.sum(axis=1)
print(a2.shape)
a3 = a.sum(axis=2)
print(a3.shape)
# over axis 1 and 2
a4 = a.sum(axis=(1,2))
print(a4.shape)

(2, 4)
(3, 4)
(3, 2)
(3,)


(2, 4)
(3, 4)
(3, 2)
(3,)
